export const MED_GLOSSARY: Record<string, string> = {
  ischemia: "Reduced blood flow to tissue, often causing oxygen shortage.",
  "myocardial infarction":
    "Heart attack; death of heart muscle due to prolonged ischemia.",
  edema: "Swelling caused by excess fluid trapped in the body's tissues.",
  lesion: "A region of abnormal tissue change.",
  benign: "Not harmful in effect; not malignant.",
  malignant:
    "Tending to invade and destroy nearby tissue and spread to other parts of the body.",
  hematoma:
    "A collection of blood outside of blood vessels, typically clotted.",
  demarcation: "A clear boundary between normal and abnormal tissue.",
  sclerosis: "Abnormal hardening of body tissue.",
  ventricle:
    "A chamber of the heart; in neuroanatomy, cavities within the brain that contain cerebrospinal fluid.",
  parenchyma:
    "The functional tissue of an organ as distinguished from the connective and supporting tissue.",
  atrophy: "Partial or complete wasting away of a body part or tissue.",
  hyperintense:
    "Appearing brighter than surrounding tissue on certain MRI sequences.",
  hypointense:
    "Appearing darker than surrounding tissue on certain MRI sequences.",
  "contrast enhancement":
    "Increased visibility of tissue on imaging after contrast agent administration.",
  aneurysm: "An abnormal bulge in the wall of a blood vessel.",
  thrombosis: "Formation of a blood clot inside a blood vessel.",
  embolism:
    "Sudden blockage of an artery by a clot or foreign material traveling in the bloodstream.",
  metastasis:
    "Spread of cancer cells from the original site to other parts of the body.",
  lumbar: "Lower part of the spine between the rib cage and pelvis.",
  cranium: "The skull, especially the part enclosing the brain.",
  cerebrospinal: "Relating to the brain and spinal cord.",
  neural: "Pertaining to the nerves or nervous system.",
  neuropathy: "Damage or dysfunction of one or more nerves.",
  synapse: "The junction between two nerve cells.",
  neuron: "A nerve cell that transmits electrical signals.",
  glial: "Supporting cells that protect and nourish neurons.",
  ischemic: "Pertaining to or affected by ischemia.",
  angiogram: "An imaging test that uses X-rays to view blood vessels.",
  catheter: "A thin tube inserted into the body for medical purposes.",
  biopsy: "Removal of a small sample of tissue for examination.",
  carcinoma:
    "A type of cancer that begins in the skin or tissue lining organs.",
  sarcoma: "A type of malignant tumor derived from connective tissue.",
  lymphoma: "Cancer that begins in cells of the lymphatic system.",
  leukemia:
    "Cancer of the body's blood-forming tissues, including bone marrow.",
  melanoma: "A type of skin cancer that develops from pigment-producing cells.",
  neoplasm: "An abnormal growth of tissue, which may be benign or malignant.",
  hyperplasia: "An increase in the number of cells in a tissue or organ.",
  hypertrophy:
    "An increase in the size of cells, leading to tissue enlargement.",
  hypoplasia: "Incomplete or underdevelopment of a tissue or organ.",
  necrosis: "The death of body tissue due to lack of blood flow or injury.",
  fibrosis: "Thickening or scarring of connective tissue.",
  infarction: "Tissue death due to inadequate blood supply.",
  ischemic_stroke:
    "A type of stroke caused by blockage in blood flow to the brain.",
  hemorrhagic_stroke: "A stroke caused by bleeding within or around the brain.",
  tachycardia: "Abnormally fast heart rate.",
  bradycardia: "Abnormally slow heart rate.",
  arrhythmia: "An irregular heartbeat.",
  hypertension: "High blood pressure.",
  hypotension: "Low blood pressure.",
  myocardial: "Related to the muscular tissue of the heart.",
  pericardium: "The membrane enclosing the heart.",
  endocardium: "The inner lining of the heart chambers.",
  angioplasty: "A procedure to restore blood flow through an artery.",
  stent: "A small mesh tube used to keep arteries open.",
  dialysis:
    "A process that removes waste products from the blood when kidneys fail.",
  renal: "Relating to the kidneys.",
  nephron: "The basic structural unit of the kidney.",
  glomerulus: "A cluster of capillaries that filters blood in the kidney.",
  hepatocyte: "A liver cell.",
  hepatic: "Relating to the liver.",
  cirrhosis: "Chronic liver damage leading to scarring and liver failure.",
  pancreatitis: "Inflammation of the pancreas.",
  insulin: "A hormone that regulates blood sugar.",
  glucose: "A simple sugar that is the body’s main energy source.",
  metabolism: "The chemical processes that occur within a living organism.",
  enzyme: "A protein that speeds up biochemical reactions.",
  hormone: "A chemical messenger produced by glands.",
  endocrine:
    "Relating to glands that secrete hormones directly into the blood.",
  exocrine: "Relating to glands that release secretions through ducts.",
  thyroid: "A gland in the neck that regulates metabolism.",
  pituitary: "The master gland controlling other glands.",
  adrenal: "Glands on top of the kidneys producing stress hormones.",
  cortisol: "A hormone released during stress.",
  epinephrine:
    "Also known as adrenaline; a hormone that increases heart rate and energy.",
  hemoglobin: "A protein in red blood cells that carries oxygen.",
  platelet: "A small blood cell involved in clotting.",
  plasma: "The liquid component of blood.",
  leukocyte: "A white blood cell that fights infection.",
  erythrocyte: "A red blood cell that carries oxygen.",
  anemia:
    "A condition marked by a deficiency of red blood cells or hemoglobin.",
  macrophage: "A large immune cell that engulfs pathogens and debris.",
  antigen: "A substance that triggers an immune response.",
  antibody: "A protein that identifies and neutralizes foreign objects.",
  pathogen: "A bacterium, virus, or microorganism that causes disease.",
  inflammation: "The body’s response to injury or infection.",
  autoimmune: "When the immune system attacks the body’s own tissues.",
  vaccine: "A preparation that stimulates an immune response for protection.",
  antibiotic: "A drug that kills or inhibits bacterial growth.",
  antiviral: "A drug used to treat viral infections.",
  analgesic: "A medication that relieves pain.",
  antipyretic: "A drug used to reduce fever.",
  anesthetic: "A drug that induces loss of sensation or awareness.",
  sedative: "A substance that promotes calm or sleep.",
  stimulant: "A substance that increases alertness or energy.",
  antidepressant: "A medication used to treat depression.",
  antipsychotic: "A drug used to manage psychosis.",
  placebo: "An inactive substance used as a control in testing new drugs.",
};
